name: alarm_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.9.2
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  intl: ^0.20.2

  # river pod
  flutter_riverpod: ^3.1.0
  riverpod_annotation: ^4.0.0

  # freezed
  freezed_annotation: ^3.1.0

  # json
  json_annotation: ^4.9.0

  # NoSQL Local DB
  hive_ce: ^2.16.0
  hive_ce_flutter: ^2.3.3

  # notification
  flutter_local_notifications: ^19.5.0

  # timezone
  timezone: ^0.10.1
  flutter_timezone: ^5.0.1

  # tts
  flutter_tts: ^4.2.3

  # alarm
  alarm: ^5.1.5

  # permission
  permission_handler: ^12.0.1

  # vibration
  vibration: ^3.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

  build_runner: ^2.10.4
  riverpod_generator: ^4.0.0+1
  freezed: ^3.2.3
  json_serializable: ^6.11.2

  hive_ce_generator: ^1.10.0

  flutter_launcher_icons: ^0.14.4
  flutter_native_splash: ^2.4.7
flutter:
  uses-material-design: true

  assets:
    - assets/sounds/

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/app_icon.png"
  min_sdk_android: 21

flutter_native_splash:
  color: "#11121C"
  image: assets/icons/splash_icon.png
  ios: true
  android: true
  fullscreen: true
  android_12:
    icon_background_color: "#11121C"
    image: assets/icons/splash_icon.png
